export const INGESTION_SOURCE_IDS = {
  BUILD: 'BUILD-SETTINGS',
  ALERTS: 'ALERTS',
  SERVICE: 'DEVOPS-SERVICE',
  ENVIRONMENTS: 'ENVIRONMENTS',
  PIPELINES: 'PIPELINES',
  PROJECTS: 'PROJECTS',
  PULL_REQUESTS: 'PULL_REQUESTS',
  REPOS: 'REPOS',
  TEAMS: 'TEAMS',
  USERS: 'USERS',
  WORK_ITEMS: 'WORK_ITEMS',
};
